version: 0.2

phases:
  build:
    commands:
      - echo Build step skipped (static site).
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync . s3://$S3_BUCKET_NAME/ --delete
artifacts:
  files:
    - '**/*'
